jobs:
  build:
    docker:
      - image: python:3.6                   # similar to "image" in GitLab
    steps:
      - checkout
      - run: |                              # similar to "script" in GitLab
          pip install -r requirements.txt
          python manage.py check

  test:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: |
          pip install -r requirements.txt
          python manage.py test taskManager

<<<<<<< HEAD
=======
  release:
    machine: true                                        # What is this for?
    steps:
      - checkout

      - run: |
          docker build -t $DOCKER_USERNAME/django.nv .   # Build the application into Docker image
          docker push $DOCKER_USERNAME/django.nv         # Push the image into registry
>>>>>>> eb7be02f9eeae08b221f516a4884dd4192205b28
  integration:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          command: |
            echo "This is an integration step"
            exit 1
<<<<<<< HEAD
=======
          when: always                    # Even if the job fails, continue to the next stages
>>>>>>> eb7be02f9eeae08b221f516a4884dd4192205b28

  prod:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: echo "This is a deploy step."

workflows:
  version: 2
  django:
    jobs:
      - build
      - test:
          requires:
            - build 
      - integration:
          requires:
            - test
      - prod:
          type: approval
          requires:
            - integration
